namespace EmpireAtWar.Components.AttackComponent
{
    public enum WeaponType
    {
        TurboLaser = 1,
        HeavyTurboLaser = 2,
        DualHeavyTurboLaser = 3,
        MediumTurboLaser = 4,
        DualMediumTurboLaser = 5,
        ProtonTorpedo = 6,
        DualLaser = 7,
        Laser = 8,
        DualHeavyTurboLaserDby827 = 9,
        IonCannon = 10,
        HeavyIonCannon = 11,
        LaserBeam = 12,
        ConcussionMissile = 13,
        PointDefense = 14,
        FighterLaser = 15,
        PlanetaryIonCannon = 16,
        HypervelocityGun = 17,
        PlasmaCannon = 18,
        MassDriver = 19,
        QuadTurboLaser = 20,
        HeavyFighterLaser = 21,
        FighterProtonTorpedo = 22,
        MediumLaser = 23,
        XWingLaser = 24,
        MediumLargeProtonTorpedo = 25,
        MediumIonTorpedo = 26,
        LightCloseRangeTurbolaser = 27,
        HeavyLaser = 28,
        LightRepeatingLaser = 29,
        FighterConcussionMissile = 30,
        HeavyArtilleryRocket = 34,
        BarrageRocket = 35,
        LightDualTurbolaser = 36,
    }
}
