// ShipWreck.shader
// -----------------------------------------------------------------------------
// A destroyed ship: the Ship Lit surface on the ship's own meshes, cut into 2-5 parts.
// The parts drift apart, tilt and sink, torn edges glow and cool, then the hull dissolves.
// Purely visual: no physics, no per-frame C# work. Cuts and timing are written into the
// material once per spawn (UnitWreckView.cs) from UnitWreckData.
// Materials and prefab are generated by Tools/Rendering/Build Wreck From Selected View.
// -----------------------------------------------------------------------------
Shader "EmpireAtWar/Ship Wreck"
{
    Properties
    {
        [Header(Surface)]
        [MainTexture] _BaseMap("Albedo", 2D) = "white" {}
        [MainColor] _BaseColor("Color", Color) = (1, 1, 1, 1)
        [NoScaleOffset] _MetallicGlossMap("Metallic (R) Smoothness (A)", 2D) = "white" {}
        _Metallic("Metallic", Range(0.0, 1.0)) = 0.0
        _Smoothness("Smoothness", Range(0.0, 1.0)) = 0.5
        [NoScaleOffset][Normal] _BumpMap("Normal Map", 2D) = "bump" {}
        _BumpScale("Normal Strength", Float) = 1.0
        [NoScaleOffset] _OcclusionMap("Occlusion (G)", 2D) = "white" {}
        _OcclusionStrength("Occlusion Strength", Range(0.0, 1.0)) = 1.0
        [NoScaleOffset] _EmissionMap("Emission", 2D) = "white" {}
        [HDR] _EmissionColor("Emission Color", Color) = (0, 0, 0, 1)

        [Header(Team Color)]
        [NoScaleOffset] _TeamMaskMap("Team Mask (R)", 2D) = "black" {}
        _TeamMaskStrength("Mask Strength", Range(0.0, 1.0)) = 1.0
        _TeamRimStrength("Rim Strength", Range(0.0, 4.0)) = 0.6
        _TeamRimPower("Rim Sharpness", Range(0.5, 8.0)) = 3.0
        _TeamEmissionTint("Emission Tint", Range(0.0, 1.0)) = 0.5
        _TeamLiveryHue("Livery Hue", Range(0.0, 1.0)) = 0.0
        _TeamLiveryHueRange("Livery Hue Range", Range(0.01, 0.5)) = 0.07
        _TeamLiveryMinSaturation("Livery Min Saturation", Range(0.0, 1.0)) = 0.4
        _TeamLiveryStrength("Livery Strength", Range(0.0, 1.0)) = 0.0

        // Written at runtime from UnitWreckData; the defaults only matter for previews.
        [Header(Wreck (set from UnitWreckData at runtime))]
        _WreckAxis("Long Axis (world space)", Vector) = (1, 0, 0, 0)
        _WreckCenter("Center (world space)", Vector) = (0, 0, 0, 0)
        _WreckCuts("Cuts (sorted, unused = 1000000)", Vector) = (0, 1000000, 1000000, 1000000)
        _WreckAxisRange("Axis Range (min, max)", Vector) = (-1, 1, 0, 0)
        _WreckSeed("Seed", Float) = 0
        _WreckStartTime("Start Time", Float) = 0
        _WreckLifetime("Lifetime", Float) = 30
        _WreckDissolveDuration("Dissolve Duration", Float) = 8
        _WreckSeparationSpeed("Separation Speed", Float) = 1.5
        _WreckTiltSpeed("Tilt Speed", Float) = 2
        _WreckSinkSpeed("Sink Speed", Float) = 1
        _WreckGlowDuration("Glow Duration", Float) = 8
        _WreckTornEdgeWidth("Torn Edge Width", Float) = 4
        [HDR] _WreckHeatColor("Heat Color", Color) = (4, 1.2, 0.2, 1)
        [HDR] _WreckDissolveEdgeColor("Dissolve Edge Color", Color) = (6, 2, 0.4, 1)
        _WreckDissolveEdgeWidth("Dissolve Edge Width", Range(0.0, 0.5)) = 0.08
        _WreckDissolveNoiseScale("Dissolve Noise Scale", Float) = 0.05

        [HideInInspector] _Cutoff("Alpha Cutoff", Range(0.0, 1.0)) = 0.5
    }

    SubShader
    {
        Tags
        {
            "RenderType" = "Opaque"
            "RenderPipeline" = "UniversalPipeline"
            "Queue" = "AlphaTest"
        }

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode" = "UniversalForward" }

            // Chunks are open shells: draw the inside too.
            Cull Off
            ZWrite On

            HLSLPROGRAM
            #pragma target 3.5
            #pragma vertex ShipWreckPassVertex
            #pragma fragment ShipWreckPassFragment
            #pragma shader_feature_local_fragment _ALPHATEST_ON

            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS
            #pragma multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS
            #pragma multi_compile_fragment _ _REFLECTION_PROBE_BLENDING
            #pragma multi_compile_fragment _ _REFLECTION_PROBE_BOX_PROJECTION
            #pragma multi_compile_fragment _ _REFLECTION_PROBE_ATLAS
            #pragma multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH
            #pragma multi_compile_fragment _ _SCREEN_SPACE_OCCLUSION
            #pragma multi_compile_fragment _ _LIGHT_COOKIES
            #pragma multi_compile _ _CLUSTER_LIGHT_LOOP
            #include_with_pragmas "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Fog.hlsl"

            #pragma multi_compile_instancing
            #pragma instancing_options renderinglayer
            #include_with_pragmas "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DOTS.hlsl"

            #define SHIP_WRECK
            #include "ShipLitInput.hlsl"
            #include "ShipWreckForwardPass.hlsl"
            ENDHLSL
        }

        Pass
        {
            Name "ShadowCaster"
            Tags { "LightMode" = "ShadowCaster" }

            ZWrite On
            ZTest LEqual
            ColorMask 0
            Cull Off

            HLSLPROGRAM
            #pragma target 3.5
            #pragma vertex ShipWreckShadowVertex
            #pragma fragment ShipWreckShadowFragment
            #pragma shader_feature_local_fragment _ALPHATEST_ON

            #pragma multi_compile_instancing
            #include_with_pragmas "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DOTS.hlsl"
            #pragma multi_compile_vertex _ _CASTING_PUNCTUAL_LIGHT_SHADOW

            #define SHIP_WRECK
            #include "ShipLitInput.hlsl"
            #include "ShipWreckDepthPasses.hlsl"
            ENDHLSL
        }

        Pass
        {
            Name "DepthOnly"
            Tags { "LightMode" = "DepthOnly" }

            ZWrite On
            ColorMask R
            Cull Off

            HLSLPROGRAM
            #pragma target 3.5
            #pragma vertex ShipWreckDepthVertex
            #pragma fragment ShipWreckDepthFragment
            #pragma shader_feature_local_fragment _ALPHATEST_ON

            #pragma multi_compile_instancing
            #include_with_pragmas "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DOTS.hlsl"

            #define SHIP_WRECK
            #include "ShipLitInput.hlsl"
            #include "ShipWreckDepthPasses.hlsl"
            ENDHLSL
        }

        Pass
        {
            Name "DepthNormals"
            Tags { "LightMode" = "DepthNormals" }

            ZWrite On
            Cull Off

            HLSLPROGRAM
            #pragma target 3.5
            #pragma vertex ShipWreckDepthVertex
            #pragma fragment ShipWreckDepthNormalsFragment
            #pragma shader_feature_local_fragment _ALPHATEST_ON

            #pragma multi_compile_instancing
            #include_with_pragmas "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DOTS.hlsl"

            #define SHIP_WRECK
            #include "ShipLitInput.hlsl"
            #include "ShipWreckDepthPasses.hlsl"
            ENDHLSL
        }
    }

    FallBack "Hidden/Universal Render Pipeline/FallbackError"
}
