using EmpireAtWar.Components.TeamColor;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace EmpireAtWar.Tests.Editor
{
    /// <summary>
    /// Unit prefabs are regenerated by editor builders; a stale renderer list throws when a unit spawns.
    /// Fix failures with Tools/Empire At War/Rendering/Materials/Add Team Color Views To Unit Prefabs.
    /// </summary>
    public sealed class TeamColorViewPrefabTests
    {
        private const string AUTODESK_SHADER_NAME = "Autodesk Interactive";

        private static readonly string[] UNIT_PREFAB_FOLDERS =
        {
            "Assets/Prefabs/Models/Ships",
            "Assets/Prefabs/Models/Stations",
            "Assets/Prefabs/Models/DefendStation",
            "Assets/Prefabs/Models/MiningFacilities",
            "Assets/Prefabs/Models/Squadrons"
        };

        [Test]
        public void TeamColorViews_ListEveryMeshRendererWithoutMissingEntries()
        {
            int checkedViews = 0;
            foreach (string guid in AssetDatabase.FindAssets("t:Prefab", UNIT_PREFAB_FOLDERS))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                TeamColorView view = prefab.GetComponent<TeamColorView>();
                if (view == null)
                {
                    continue;
                }

                SerializedProperty renderers = new SerializedObject(view).FindProperty("meshRenderers");
                for (int i = 0; i < renderers.arraySize; i++)
                {
                    Assert.That(renderers.GetArrayElementAtIndex(i).objectReferenceValue, Is.Not.Null,
                        $"{path}: meshRenderers[{i}] is missing.");
                }

                Assert.That(renderers.arraySize,
                    Is.EqualTo(prefab.GetComponentsInChildren<MeshRenderer>(true).Length),
                    $"{path}: the team color view does not list every mesh renderer.");
                // Autodesk Interactive materials ignore team colors; units must use their Ship Lit copies.
                foreach (MeshRenderer meshRenderer in prefab.GetComponentsInChildren<MeshRenderer>(true))
                {
                    foreach (Material material in meshRenderer.sharedMaterials)
                    {
                        if (material == null)
                        {
                            continue;
                        }

                        Assert.That(material.shader.name, Does.Not.Contain(AUTODESK_SHADER_NAME),
                            $"{path}: {meshRenderer.name} still uses {material.name}.");
                    }
                }

                checkedViews++;
            }

            Assert.That(checkedViews, Is.GreaterThan(0));
        }
    }
}
